### PR TITLE
Refactor AgentPopulation/AgentInstance

### LINKED ISSUE #117: AgentPopulation::getNextInstance(char*) is misleading
This function creates a new agent and returns that agent. It's name should imply this, it's current name suggests it's some kind of iterator.

Similarly, it would be worth documenting the class properly, to clarify that construction allocates initial memory, but does not create uninitialised agents.

### PR DESCRIPTION
**Pull request by Robadob**
Replaces `AgentPopulation` with new classes `AgentVector`, `AgentVector::Agent`. These have an interface similar to what a `std::vector` of agents would look like, but store data as SoA internally.
`AgentInstance` has also been created, to pass around standalone data for a single agent.
Both C and Py interfaces have full test suites.
Py interface lacks access to `AgentVector` iterator (and some util) methods.
Related to #246 #237
Closes #117

### CODE REVIEW

**Comment by Robadob** [comment]
SWIG version of `AgentVector` doesn't have an `AgentVector::erase()` equivalent. The proper equivalent would be pythons `pop()` function but that returns the erased item Which in this case would be an `AgentElement`.

This same issue applies to `RunPlanVec` (they use the same SWIG hack for making it usable like a python list). Although I haven't checked how `RunPlanVec` handles deletion of items in C.

**Comment by Robadob** [comment]
todo rename `AgentView` to `AgentVector::View`

**Comment by Robadob** [comment]
> SWIG version of AgentVector doesn't have an AgentVector::erase() equivalent. The proper equivalent would be pythons pop() function but that returns the erased item Which in this case would be an AgentElement.

I just gave swig a copy of C insert/erase which take size_type rather than iterator, and have no return value (rather than returning an iterator).

**Review by ptheywood — APPROVED** [review]
I've not reviewed all ~10k changes, but both test suites pass under linux

**Pull request merged**
