### PR TITLE
Replace BoostTest -> GoogleTest

### PR DESCRIPTION
**Pull request by Robadob**
# This branch should be 'Rebase & Merge'd!
## Else dependent branches will have conflicts

This branch was setup to test GoogleTest as a drop in for BoostTest, but it's worked better than expected.

**Benefits:**
* No build warnings
* No runtime errors
* Faster/easier to setup than BoostTest
* Tests can be compiled separately, rather than needing to be one big compilation unit.

**Changelog:**
Replaces BoostTest with GoogleTest, and other minor changes:
* Fixes broken tests and updates readme to refer to googletest.
* General improvements to the appveyor script:
  + Simple selection of CUDA Version
  + Support for VS 2017
    + Only using CUDA 10.1.243
  + Support for VS 2019
    + For CUDA 10.1 and greater
  + Appveyor now set to CUDA 10.1.243 and VS 2019 by default 
* Fixes VS 2017+ warning re: types for tolower.
* Adds parallel compilation for FGPU2.lib to Visual studio
* Adds parallel compilation details to README for Linux users

**Test it works for:**
  - [x] CI
  - [x] Pete
  - [ ] Mozghan
  - [ ] Paul

...
(and eventually enable tests on internal CI)

### CODE REVIEW

**Comment by ptheywood** [comment]
If network acces is down at cmake configure time, it fails when trying to build tests as unable to pull google test. 

It might be better to not place googletest inside the build directory, so that it can still be built/configured if google test is brought down. 
Might also be worth making it so that users can specify thier own googletest version to build the tests without network?

```
cmake .. -DBUILD_TESTS=ON -DSMS=70
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - /usr/local/cuda-10.1/bin/nvcc
-- The CUDA compiler identification is NVIDIA 10.1.243
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CUDA compiler: /usr/local/cuda-10.1/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-10.1/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CXX compiler: /home/ptheywood/bin/modules/gcc-7/g++
-- Check for working CXX compiler: /home/ptheywood/bin/modules/gcc-7/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- -----Configuring Project: flamegpu2-----
-- Setting build type to 'Release' as none was specified.
-- Targeting Compute Capabilities: 70
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dia missing components:  mscgen dot
-- -----Configuring Project: mas-----
-- -----Configuring Project: simple_example-----
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ptheywood/code/flamegpu/flamegpu2_dev/build/tests/googletest-download
Scanning dependencies of target googletest
[ 11%] Creating directories for 'googletest'
[ 22%] Performing download step (git clone) for 'googletest'
Cloning into 'googletest-src'...
fatal: unable to access 'https://github.com/google/googletest.git/': Could not resolve host: github.com
Cloning into 'googletest-src'...
fatal: unable to access 'https://github.com/google/googletest.git/': Could not resolve host: github.com
Cloning into 'googletest-src'...
fatal: unable to access 'https://github.com/google/googletest.git/': Could not resolve host: github.com
-- Had to git clone more than once:
          3 times.
CMake Error at googletest-download/googletest-prefix/tmp/googletest-gitclone.cmake:66 (message):
  Failed to clone repository: 'https://github.com/google/googletest.git'


make[2]: *** [CMakeFiles/googletest.dir/build.make:91: googletest-prefix/src/googletest-stamp/googletest-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/googletest.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
CMake Error at tests/CMakeLists.txt:26 (message):
  Build step for googletest failed: 2


-- Configuring incomplete, errors occurred!
See also "/home/ptheywood/code/flamegpu/flamegpu2_dev/build/CMakeFiles/CMakeOutput.log".
```

**Comment by ptheywood** [comment]
Any call to cmake while network is down currently fails, even if googletest is up to date

```
cmake .. -DBUILD_TESTS=ON -DSMS=60
-- -----Configuring Project: flamegpu2-----
-- Targeting Compute Capabilities: 60
-- -----Configuring Project: mas-----
-- -----Configuring Project: simple_example-----
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ptheywood/code/flamegpu/flamegpu2_dev/build/tests/googletest-download
[ 11%] Performing update step for 'googletest'
fatal: unable to access 'https://github.com/google/googletest.git/': Could not resolve host: github.com
CMake Error at /home/ptheywood/code/flamegpu/flamegpu2_dev/build/tests/googletest-download/googletest-prefix/tmp/googletest-gitupdate.cmake:58 (message):
  Failed to fetch repository 'https://github.com/google/googletest.git'


make[2]: *** [CMakeFiles/googletest.dir/build.make:96: googletest-prefix/src/googletest-stamp/googletest-update] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/googletest.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
CMake Error at tests/CMakeLists.txt:26 (message):
  Build step for googletest failed: 2


-- Configuring incomplete, errors occurred!
See also "/home/ptheywood/code/flamegpu/flamegpu2_dev/build/CMakeFiles/CMakeOutput.log".
See also "/home/ptheywood/code/flamegpu/flamegpu2_dev/build/CMakeFiles/CMakeError.log".
```

**Comment by Robadob** [comment]
Latest commit allows it to work if already downloaded and no network, with option to disable even trying (to suppress warnings).

**Comment by mondus** [comment]
@Robadob Do you want this squashed?

**Comment by ptheywood** [comment]
I think @Robadob  wants it rebasing 

> This branch should be 'Rebase & Merge'd!

**Pull request merged**
