### PR TITLE
Increase curve max size to 1024

### PR DESCRIPTION
**Pull request by Robadob**
Tests pass on Windows x Release
Relates to #356

### CODE REVIEW

**Comment by Robadob** [comment]
Where an agent function inputs and outputs message of same name, there is a collision. This needs addressing.

**Comment by ptheywood** [comment]
> Where an agent function inputs and outputs message of same name, there is a collision. This needs addressing.

We could disable that functionality for now? I don't think that it's supported in Flamegpu 1 (although no reason it shouldn't be supported IMO).

**Comment by Robadob** [comment]
The spatial messaging tests need adjusting, they currently have the
warning.

**Comment by Robadob** [comment]
I fixed the spatial message warning issue, so I'll merge this now.

**Pull request merged**
