### PR TITLE
Split AgentData into multiple files

### PR DESCRIPTION
**Pull request by ptheywood**
`include/model/AgentData.h` previously included 4 structs with partial dependency loops on each other. 

This splits them into separate header and implementation files with appropriate forward declaration, and updates includes throughout the project as required.

Also renames io/*.cu to io/*.cpp, as these files need no knowledge of cuda

### CODE REVIEW

**Comment by ptheywood** [comment]
Ok to merge after rtc merge.

**Comment by Robadob** [comment]
The github ui conflict diff isn't useful in the slightest.

I guess we need to diff master:HEAD vs 5e2a28a for `ModelData.h`, `ModelData.cpp`, then apply those changes to the affected files.

**Comment by Robadob** [comment]
Also noticed he forgot to update `AgentFunctionData::operator==()`, it was also missing several members related to agent function conditions/agent output. I've fixed this in my presumed conflict resolve.

**Comment by Robadob** [comment]
Builds, lints and tests pass on Windows, doesn't on Travis. LayerDescription might need to be Cu due to it including Message headers.
Todo:
Fix Travis issue
Review `ModelData.cpp` includes.
(I left them like this as i wasn't sure in merge)
```C
//<<<<<< HEAD
#include "flamegpu/model/LayerDescription.h"
#include "flamegpu/runtime/messaging/BruteForce.h"
#include "flamegpu/runtime/cuRVE/curve_rtc.h"

///=======
#include "flamegpu/model/AgentFunctionData.h"
#include "flamegpu/model/LayerData.h"
//>>>>>>> Split AgentData into multiple files
```

**Comment by ptheywood** [comment]
builds/passes test under linux now, so should be fine to sqush merge once CI is done.

**Pull request merged**
